version: '3'

services:
  api:
    image: identicum/opa-demoapi-spring:latest
    restart: always
    ports:
     - 8081:8081
    extra_hosts:
     - "opa:110.1.2.123"    
 # opa:
 #   image: openpolicyagent/opa:latest
 #   restart: always
 #   ports:
 #     - 8181:8181
 #   volumes:
 #     - ./policies.rego:/policies.rego
 #   command:
 #   - "run"
 #   - "--server"
 #   - "--watch"
 #   - "--log-level=debug"
 #   - "/policies.rego"

## Examples
# docker-compose up
# docker-compose up -d ht-portal
# docker-compose down