server:
  port: 8089

opa:
  url: http://opa:8181/v1/data
  bundle: http/authz
  rule: allow

logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.identicum: DEBUG
